--------------------------------------
-- 1. Table: profiles (Extended Auth)
--------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  full_name TEXT,
  email TEXT UNIQUE,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view their own profile
CREATE POLICY "Users can view own profile" ON public.profiles
  FOR SELECT USING (auth.uid() = id);

-- Policy: Users can update their own profile
CREATE POLICY "Users can update own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-----------------------------------------
-- 2. Table: subscriptions (Management)
-----------------------------------------
CREATE TABLE IF NOT EXISTS public.subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  plan_name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING', -- 'ACTIVE', 'PENDING', 'EXPIRED'
  start_date TIMESTAMPTZ DEFAULT now(),
  end_date TIMESTAMPTZ,
  xendit_reference TEXT UNIQUE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Create unique index: one active subscription per user
CREATE UNIQUE INDEX IF NOT EXISTS single_subscription ON public.subscriptions (user_id) WHERE status = 'ACTIVE';

-- Enable RLS
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view their own subscriptions
CREATE POLICY "Users can view own subscriptions" ON public.subscriptions
  FOR SELECT USING (auth.uid() = user_id);

--------------------------------------------
-- 3. Table: xendit_transactions (Auditing)
--------------------------------------------
CREATE TABLE IF NOT EXISTS public.xendit_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  external_id TEXT UNIQUE NOT NULL,
  amount NUMERIC(10, 2) NOT NULL,
  payment_method TEXT NOT NULL,
  plan_name TEXT,
  xendit_invoice_id TEXT UNIQUE,
  status TEXT NOT NULL DEFAULT 'PENDING', -- 'PENDING', 'PAID', 'EXPIRED'
  callback_received BOOLEAN DEFAULT FALSE,
  callback_payload JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  paid_at TIMESTAMPTZ
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_xendit_invoice_id ON public.xendit_transactions (xendit_invoice_id);
CREATE INDEX IF NOT EXISTS idx_external_id ON public.xendit_transactions (external_id);

-- Enable RLS
ALTER TABLE public.xendit_transactions ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view their own transactions
CREATE POLICY "Users can view own transactions" ON public.xendit_transactions
  FOR SELECT USING (auth.uid() = user_id);

----------------------------------------------
-- 4. Function: handle_xendit_payment_success
----------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_xendit_payment_success(
  p_external_id TEXT,
  p_xendit_id TEXT,
  p_callback_payload JSONB
)
RETURNS VOID AS $$
DECLARE
  v_user_id UUID;
  v_plan_name TEXT;
BEGIN
  -- Update status transaksi dan mendapatkan user_id/plan_name
  UPDATE public.xendit_transactions
  SET 
    status = 'PAID',
    xendit_invoice_id = p_xendit_id,
    callback_received = TRUE,
    callback_payload = p_callback_payload,
    paid_at = now()
  WHERE external_id = p_external_id
  RETURNING user_id, plan_name INTO v_user_id, v_plan_name;

  -- Update/Buat Langganan Baru (Contoh: Menambah 30 hari)
  IF v_user_id IS NOT NULL THEN
    INSERT INTO public.subscriptions (user_id, plan_name, status, start_date, end_date, xendit_reference)
    VALUES (v_user_id, v_plan_name, 'ACTIVE', now(), now() + INTERVAL '30 days', p_external_id)
    ON CONFLICT (user_id) WHERE status = 'ACTIVE'
    DO UPDATE SET
      plan_name = EXCLUDED.plan_name,
      status = 'ACTIVE',
      end_date = COALESCE(public.subscriptions.end_date, now()) + INTERVAL '30 days',
      updated_at = now(),
      xendit_reference = EXCLUDED.xendit_reference;
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execute permission to authenticated users
GRANT EXECUTE ON FUNCTION public.handle_xendit_payment_success TO authenticated;
GRANT EXECUTE ON FUNCTION public.handle_xendit_payment_success TO service_role;
